### ISSUE TITLE
【全般】APIを使ってアップロードしたファイルの内容が暗号化されない

### ISSUE THREAD

**Issue by wreathvine** [exastro-suite/it-automation#1036]
## 概要
APIを使ってアップロードしたファイルの内容が暗号化されない。

## 期待される挙動
APIを使ってアップロードした場合、ファイルの内容が暗号化される。

#### 画面からの登録時(OKパターン)
▼ユースケース
機器一覧に手動で機器情報を登録する場合
▼手順
A-1. 「機器一覧」の対象機器に対して、SSH秘密鍵をファイルアップロードする。
▼結果
登録したSSH秘密鍵を利用してSSH接続に成功する。
#### API からの登録時(NGパターン)
▼ユースケース
事前にSSH公開鍵を登録したサーバをITAで作成し、そのサーバに対してSSH接続をし、変更を加える場合
▼手順
B-1. SSH秘密鍵を BASE64 エンコードする。
B-2.「入力用」のメニューに BASE64 エンコード済みのSSH秘密鍵(エンコード済み秘密鍵)をパスワードとして登録する。
B-3. B-2のエンコード済み秘密鍵を入力値として利用して、REST API を使って「機器一覧」にサーバ情報を登録する。(登録されたサーバ情報には暗号化(ky_encrypt())されていない状態でSSH秘密鍵が保存される)
▼API登録時のAnsibleのタスク
```YAML
- name: 「VMリストファイル」に存在しており「機器一覧」に存在しないデータは「登録」
  uri:
    url: "https://{{ __loginhostname__ }}/default/menu/07_rest_api_ver1.php?no=2100000303"
    validate_certs: no
    method: POST
    headers:
      Host: "{{ __loginhostname__ }}:443"
      Authorization: "{{ user_n_account.stdout | string | b64encode }}"
      Content-Type: "application/json"
      X-Command: "EDIT"
    body_format: json
    body:
      "0":
        "0": "登録"
        "3": "SV"
        "4": "{{ item.0 }}"
        "5": "{{ item.1 }}"
        "8": "{{ VAR_vm_user }}"
        "11": "{{ VAR_keypair_name }}"
        "13": "鍵認証(パスフレーズなし)\ "
        "21": "machine"
        "29": "ホストグループ：{{ VAR_hostgroup_name }}"
      "UPLOAD_FILE":
        "0":
          "11": "{{ VAR_keypair_contents }}"
  when:
    - device_list_from_exastro_hostnames.results | map(attribute='ansible_facts.host_name') | list | select('match', item.0) | length == 0
  with_together:
    - "{{ vm_info_from_file | map(attribute='public_dns_name') | list }}"
    - "{{ vm_info_from_file | map(attribute='public_ip_address') | list }}"
```

▼結果
SSHログインを試みた際に、暗号化されていないファイルを復号するためファイルが破損し結果としてSSH 接続に失敗する。

![image](https://user-images.githubusercontent.com/83527822/117227495-e0152c00-ae51-11eb-817b-5ec22e35761b.png)
