### ISSUE TITLE
【機器一覧】APIで機器登録時にファイル名を指定した場合でもファイルをアップロードせずに登録できてしまう。

### ISSUE THREAD

**Issue by yk-2** [exastro-suite/it-automation#1264]
# 【機器一覧】APIで機器登録時にファイル名を指定した場合でもファイルをアップロードせずに登録できてしまう。
## 再現方法
以下のPlaybookのようにSSH秘密鍵ファイル名を指定する(test.pem)。
UPLOAD_FILEを指定せずに実行。

```yml
- name: 機器一覧へ登録
  uri:
    url: http://localhost/default/menu/07_rest_api_ver1.php?no=2100000303
    headers:
      Content-Type: "application/json"
      Authorization: "{{ (item.username + ':' + item.password) | b64encode }}"
      X-Command: EDIT
    status_code: 200
    method: POST
    return_content: yes
    body:
        0:
          0: 登録
          3: SV
          4: test05
          5: 127.0.0.105
          8: username
          11: test.pem
          13: 鍵認証(パスフレーズなし)
          21: machine
    body_format: json
  register: result_edit
  loop:
    - username: "{{ VAR_ITA_USERNAME }}"
      password: "{{ VAR_ITA_PASSWORD }}"
```

## 環境
CentOS 7
ITA 1.7.2
