### ISSUE TITLE
【収集機能】Exastro収集機能でパラメータシートに正しくデータが設定されないように見える

### ISSUE THREAD

**Issue by dai-kagino** [exastro-suite/it-automation#1767]
###  事象
Exastro 収集機能により収集したデータを収集項目値管理でパラメータシートに代入しようとした際、正しく値が連携されていないように見えます。
（詳細は後述）
確認を実施した環境のkym、参照用メニューxls、収集項目値管理xls、および収集データを添付させていただきます。
他に採取必要な情報などありましたらご教示ください。

**Comment by dai-kagino** [comment]
[メニューエクスポートファイル](https://github.com/exastro-suite/it-automation/files/7782292/ita_exportdata_20211228104819.zip)
[収集データ](https://github.com/exastro-suite/it-automation/files/7782295/ResultData_0000000001.zip)
[収集項目値管理xls](https://github.com/exastro-suite/it-automation/files/7782298/_20211228104852.xlsx)
[パラメータシート(参照用)](https://github.com/exastro-suite/it-automation/files/7782299/Windows2019_ErrorReporting_20211228104812.xlsx)

★管理対象となる収集データファイルは、"WIN_ErrorReporting_ITA.yml" になります。

**Comment by dai-kagino** [comment]
収集データを見ると、最初の４つのデータが以下のようになっています。
```
VAR_WIN_ErrorReporting:
- Key: '''HKLM:\SOFTWARE\Microsoft\Windows\Windows Error Reporting'''
  Values:
  - Action: '''present'''
    Value: '1'
    ValueName: '''EnableZip'''
    ValueType: '''REG_DWORD'''
- Key: '''HKLM:\SOFTWARE\Microsoft\Windows\Windows Error Reporting'''
  Values:
  - Action: '''present'''
    Value: '''\WindowsErrorReportingServicePort'''
    ValueName: '''ErrorPort'''
    ValueType: '''REG_SZ'''
- Key: '''HKLM:\SOFTWARE\Microsoft\Windows\Windows Error Reporting'''
  Values:
  - Action: '''present'''
    Value: '60000'
    ValueName: '''ServiceTimeout'''
    ValueType: '''REG_DWORD'''
- Key: '''HKLM:\SOFTWARE\Microsoft\Windows\Windows Error Reporting\Assert Filtering Policy'''
  Values:
  - Action: '''present'''
    Value: '1'
    ValueName: '''ReportAndContinue'''
    ValueType: '''REG_DWORD'''
```
