### ISSUE TITLE
【収集】空の収集データ(null)が正しくパラメータシートに反映されない

### ISSUE THREAD

**Issue by dai-kagino** [exastro-suite/it-automation#1936]
収集を行った際に、空の収集データ(null)が正しくパラメータシートに反映されないケースが存在する。

以下、発生時手順

1. /home 配下のディレクトリ一覧を収集するジョブを作成

2. ユーザフォルダを追加
ターゲットでコマンド実行
    ```
    [root@Target home]# useradd user2
    [root@Target home]# ls
    user  user2
    ```

3. ジョブ実行
RH_directory_ITA_0009000001.zip（RH_directory_ITA.yml）
    ```
    VAR_RH_directory_ITA:
    - action: directory
      dir_path: /home/user
      group: user
      mode: u=rwx,g=,o=
      owner: user
      symbolic_link: null
    - action: directory
      dir_path: /home/user2
      group: user2
      mode: u=rwx,g=,o=
      owner: user2
      symbolic_link: null
    - action: null
      dir_path: null
      group: null
      mode: null
      owner: null
      symbolic_link: null
    ```

4. ジョブ実行後のパラメータシート
　directory_RHEL8_0009000001.xlsx
    | action | dir_path | group | mode | owner | symbolic_link |
    | --- | --- | --- | --- | --- |  --- | 
    | directory | /home/user | user | u=rwx,g=,o= | user | 　 | 
    | directory | /home/user2 | user2 | u=rwx,g=,o= | user2 | 　 | 
    | 　 | 　 | 　 | 　 | 　 | 　 | 

5. ユーザフォルダを削除
ターゲットでコマンド実行
    ```
    [root@Target home]# userdel user2
    [root@Target home]# rm -rf /home/user2/
    [root@Target home]# ls
    user
    ```

6. ジョブ実行
RH_directory_ITA_0009000002.zip（RH_directory_ITA.yml）
    ```
    VAR_RH_directory_ITA:
    - action: directory
      dir_path: /home/user
      group: user
      mode: u=rwx,g=,o=
      owner: user
      symbolic_link: null
    - action: null
      dir_path: null
      group: null
      mode: null
      owner: null
      symbolic_link: null
    - action: null
      dir_path: null
      group: null
      mode: null
      owner: null
      symbolic_link: null
    ```

7. ジョブ実行後のパラメータシート
　directory_RHEL8_0009000001.xlsx
    | action | dir_path | group | mode | owner | symbolic_link |
    | --- | --- | --- | --- | --- |  --- | 
    | directory | /home/user | user | u=rwx,g=,o= | user | 　 | 
    | 　 | /home/user2 | user2 | u=rwx,g=,o= | user2 | 　 | 
    | 　 | 　 | 　 | 　 | 　 | 　 | 

- ジョブ実行後のパラメータシートの期待値
（user2のデータがクリアされた状態）
    | action | dir_path | group | mode | owner | symbolic_link |
    | --- | --- | --- | --- | --- |  --- | 
    | directory | /home/user | user | u=rwx,g=,o= | user | 　 | 
    | 　 | 　 | 　 | 　 | 　 | 　 | 
    | 　 | 　 | 　 | 　 | 　 | 　 |
